version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prepsquad-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      # Prevent overwriting node_modules
      - /app/venv
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    restart: unless-stopped
    networks:
      - prepsquad-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: prepsquad-frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - prepsquad-network

networks:
  prepsquad-network:
    driver: bridge
